<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Isaias Echenique">

<title>Avance 4</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Avance 4_files/libs/clipboard/clipboard.min.js"></script>
<script src="Avance 4_files/libs/quarto-html/quarto.js"></script>
<script src="Avance 4_files/libs/quarto-html/popper.min.js"></script>
<script src="Avance 4_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Avance 4_files/libs/quarto-html/anchor.min.js"></script>
<link href="Avance 4_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Avance 4_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Avance 4_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Avance 4_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Avance 4_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Avance 4</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Isaias Echenique </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="análisis-exploratorio" class="level1" style="text-align: center;">
<h1>Análisis Exploratorio</h1>
</section>
<section id="objetivo-predicción-de-los-precios-de-venta-de-hogares-en-ames-iowa." class="level3">
<h3 class="anchored" data-anchor-id="objetivo-predicción-de-los-precios-de-venta-de-hogares-en-ames-iowa.">1. Objetivo: Predicción de los precios de venta de hogares en Ames, Iowa.</h3>
<p>El objetivo es desarrollar un modelo que prediga el precio de venta de una determinada casa en Ames, Iowa. Los interesados en el informe esperan conocer si el precio al que se ofrece una casa está por encima o por debajo de su valor real.</p>
<p>El conjunto de datos contiene información de la Oficina del Asesor de Ames utilizada en el cálculo de los valores tasados de propiedades residenciales individuales vendidas en Ames, Iowa, desde 2006 hasta 2010.</p>
<hr>
</section>
<section id="eda-análisis-exploratorio-de-datos." class="level3">
<h3 class="anchored" data-anchor-id="eda-análisis-exploratorio-de-datos.">2. EDA: Análisis exploratorio de datos.</h3>
<p>La base de datos que se requiere se encuentra contenida en el archivo ames.csv. En el archivo análisis_ames.py se desarrolla el modelo de predicción y en él mismo se plasma el código, en el presente documento se muestran los resultados.</p>
<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> siuba <span class="im">import</span> <span class="op">*</span>  </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>ames_housing <span class="op">=</span> pd.read_csv(<span class="st">"ames.csv"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>ames_housing.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 74 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   MS_SubClass         2930 non-null   object 
 1   MS_Zoning           2930 non-null   object 
 2   Lot_Frontage        2930 non-null   int64  
 3   Lot_Area            2930 non-null   int64  
 4   Street              2930 non-null   object 
 5   Alley               2930 non-null   object 
 6   Lot_Shape           2930 non-null   object 
 7   Land_Contour        2930 non-null   object 
 8   Utilities           2930 non-null   object 
 9   Lot_Config          2930 non-null   object 
 10  Land_Slope          2930 non-null   object 
 11  Neighborhood        2930 non-null   object 
 12  Condition_1         2930 non-null   object 
 13  Condition_2         2930 non-null   object 
 14  Bldg_Type           2930 non-null   object 
 15  House_Style         2930 non-null   object 
 16  Overall_Cond        2930 non-null   object 
 17  Year_Built          2930 non-null   int64  
 18  Year_Remod_Add      2930 non-null   int64  
 19  Roof_Style          2930 non-null   object 
 20  Roof_Matl           2930 non-null   object 
 21  Exterior_1st        2930 non-null   object 
 22  Exterior_2nd        2930 non-null   object 
 23  Mas_Vnr_Type        1155 non-null   object 
 24  Mas_Vnr_Area        2930 non-null   int64  
 25  Exter_Cond          2930 non-null   object 
 26  Foundation          2930 non-null   object 
 27  Bsmt_Cond           2930 non-null   object 
 28  Bsmt_Exposure       2930 non-null   object 
 29  BsmtFin_Type_1      2930 non-null   object 
 30  BsmtFin_SF_1        2930 non-null   int64  
 31  BsmtFin_Type_2      2930 non-null   object 
 32  BsmtFin_SF_2        2930 non-null   int64  
 33  Bsmt_Unf_SF         2930 non-null   int64  
 34  Total_Bsmt_SF       2930 non-null   int64  
 35  Heating             2930 non-null   object 
 36  Heating_QC          2930 non-null   object 
 37  Central_Air         2930 non-null   object 
 38  Electrical          2930 non-null   object 
 39  First_Flr_SF        2930 non-null   int64  
 40  Second_Flr_SF       2930 non-null   int64  
 41  Gr_Liv_Area         2930 non-null   int64  
 42  Bsmt_Full_Bath      2930 non-null   int64  
 43  Bsmt_Half_Bath      2930 non-null   int64  
 44  Full_Bath           2930 non-null   int64  
 45  Half_Bath           2930 non-null   int64  
 46  Bedroom_AbvGr       2930 non-null   int64  
 47  Kitchen_AbvGr       2930 non-null   int64  
 48  TotRms_AbvGrd       2930 non-null   int64  
 49  Functional          2930 non-null   object 
 50  Fireplaces          2930 non-null   int64  
 51  Garage_Type         2930 non-null   object 
 52  Garage_Finish       2930 non-null   object 
 53  Garage_Cars         2930 non-null   int64  
 54  Garage_Area         2930 non-null   int64  
 55  Garage_Cond         2930 non-null   object 
 56  Paved_Drive         2930 non-null   object 
 57  Wood_Deck_SF        2930 non-null   int64  
 58  Open_Porch_SF       2930 non-null   int64  
 59  Enclosed_Porch      2930 non-null   int64  
 60  Three_season_porch  2930 non-null   int64  
 61  Screen_Porch        2930 non-null   int64  
 62  Pool_Area           2930 non-null   int64  
 63  Pool_QC             2930 non-null   object 
 64  Fence               2930 non-null   object 
 65  Misc_Feature        106 non-null    object 
 66  Misc_Val            2930 non-null   int64  
 67  Mo_Sold             2930 non-null   int64  
 68  Year_Sold           2930 non-null   int64  
 69  Sale_Type           2930 non-null   object 
 70  Sale_Condition      2930 non-null   object 
 71  Sale_Price          2930 non-null   int64  
 72  Longitude           2930 non-null   float64
 73  Latitude            2930 non-null   float64
dtypes: float64(2), int64(32), object(40)
memory usage: 1.7+ MB</code></pre>
</div>
</div>
<hr>
</section>
<section id="descripción-de-las-variables." class="level2">
<h2 class="anchored" data-anchor-id="descripción-de-las-variables.">Descripción de las variables.</h2>
<p>Con la información obtenida podemos observar:</p>
<ul>
<li><p><strong>Tamaño:</strong> La base de datos contiene 74 columnas con 2,930 registros</p></li>
<li><p><strong>Columnas:</strong> En cuanto a las columnas cada columna tiene un nombre (enumerado del 0 al 73) y se muestra el nombre de la columna (por ejemplo, “MS_SubClass”, “MS_Zoning”) junto con el número de valores no nulos y el tipo de datos (por ejemplo, “object”, “int64”, “float64”).</p></li>
<li><p><strong>Tipo de columnas:</strong> Las columnas contienen diferentes tipos de datos, como objetos, enteros y flotantes. Por ejemplo, “MS_SubClass” y “MS_Zoning” son columnas de tipo “object”, mientras que “Lot_Frontage” es una columna de tipo “int64”, y “Longitude” y “Latitude” son columnas de tipo “float64”.</p></li>
<li><p><strong>Valores faltantes</strong>: Algunas columnas tienen valores faltantes, como “Mas_Vnr_Type” que tiene 1,155 valores y “Misc_Feature” que tiene solo 106 valores. El número de valores de estas columnas indica la cantidad de datos disponiblesen.</p></li>
<li><p><strong>Variable</strong> <strong>objetivo</strong>: La última columna, “<strong>Sale_Price</strong>”, parece ser la variable objetivo del conjunto de datos, ya que es de tipo “int64” y puede representar los precios de venta de las viviendas.</p></li>
</ul>
<div class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<p><img src="Avance%204_files/figure-html/cell-3-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display" data-execution_count="62">
<pre><code>&lt;Figure Size: (640 x 480)&gt;</code></pre>
</div>
</div>
<div class="cell" data-execution_count="3">
<div class="cell-output cell-output-display" data-execution_count="63">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Mean_Sale_Price</th>
<th data-quarto-table-cell-role="th">Median_Sale_Price</th>
<th data-quarto-table-cell-role="th">Min_Sale_Price</th>
<th data-quarto-table-cell-role="th">Max_Sale_Price</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>180796.1</td>
<td>160000.0</td>
<td>12789</td>
<td>755000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><em>La variable “Sale_Price” tiene un rango que va desde 12,789 hasta 755,000, con un valor medio de alrededor de 180,796.1 y una mediana de 160,000.0. Estos datos estadísticos resumen la distribución de los precios de venta en el conjunto de datos, lo que proporciona información importante sobre la variabilidad de los precios de las viviendas.</em></p>
<hr>
</section>
<section id="selección-de-variables" class="level2">
<h2 class="anchored" data-anchor-id="selección-de-variables">Selección de Variables</h2>
<p>Basado en la información proporcionada en la estructura de datos y tipos de variables en el conjunto de datos, es posible identificar varias variables que podrían ser relevantes para predecir el precio de una vivienda en Ames,Iowa.</p>
<ol type="1">
<li><p>Superficie del terreno (<strong>Lot_Area</strong>): El tamaño del terreno en el que se encuentra la vivienda ya que puede influir en su precio.</p></li>
<li><p>Año de construcción (<strong>Year_Built</strong>): La antigüedad de la vivienda es un factor importante en la determinación del precio.</p></li>
<li><p>Área habitable (<strong>Gr_Liv_Area</strong>): El espacio habitable de la vivienda suele estar correlacionado con el precio.</p></li>
<li><p>Número de habitaciones (<strong>TotRms_AbvGrd</strong>): El número de habitaciones y su distribución pueden ser indicativos del tamaño y la comodidad de la vivienda.</p></li>
<li><p>Número de baños (<strong>Full_Bath y Half_Bath</strong>): La cantidad de baños también es un factor clave en la valoración de una vivienda.</p></li>
<li><p>Número de garajes (<strong>Garage_Cars</strong>): La capacidad de estacionamiento.</p></li>
<li><p>Ubicación (<strong>Latitude</strong> <strong>y</strong> <strong>Longitude</strong>): La ubicación geográfica puede afectar significativamente el precio de la vivienda.</p></li>
<li><p>Calidad de la calefacción (<strong>Heating_QC</strong>), calidad de la cocina (<strong>Kitchen_AbvGr</strong>) y otros: Los atributos indican la calidad de características específicas de la vivienda.</p></li>
<li><p>Tipo de vivienda (<strong>Bldg_Type</strong>) y estilo de la casa (<strong>House_Style</strong>): Estos factores pueden afectar la percepción sobre la vivienda.</p></li>
</ol>
<hr>
</section>
<section id="consideración-de-nuevas-variables" class="level2">
<h2 class="anchored" data-anchor-id="consideración-de-nuevas-variables">Consideración de nuevas variables</h2>
<p>Aparte de las variables antes mencionadas, se pueden calcular algunas variables derivadas o calculadas que podrían ser útiles para predecir el precio de la vivienda.</p>
<ul>
<li>Relación Precio por Pie Cuadrado: Calcular el precio por pie cuadrado dividiendo el precio de la vivienda por su área habitable. Esta métrica puede ser relevante en relación al precio.</li>
</ul>
<div class="cell" data-execution_count="4">
<div class="cell-output cell-output-display" data-execution_count="64">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Mean_Metros</th>
<th data-quarto-table-cell-role="th">Median_Metros</th>
<th data-quarto-table-cell-role="th">First_Metros</th>
<th data-quarto-table-cell-role="th">Last_Metros</th>
<th data-quarto-table-cell-role="th">Min_Metros</th>
<th data-quarto-table-cell-role="th">Max_Metros</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>21.537993</td>
<td>18.005914</td>
<td>6.767391</td>
<td>19.52841</td>
<td>0.898245</td>
<td>97.482639</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<ul>
<li><p>Antigüedad: Calcular la edad de la vivienda en el año de venta restando el año de construcción del año de venta (Antique = Year_Sold - Year_Built).</p>
<div class="cell" data-execution_count="5">
<div class="cell-output cell-output-display" data-execution_count="65">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Mean_Antique</th>
<th data-quarto-table-cell-role="th">Median_Antique</th>
<th data-quarto-table-cell-role="th">First_Antique</th>
<th data-quarto-table-cell-role="th">Last_Antique</th>
<th data-quarto-table-cell-role="th">Min_Antique</th>
<th data-quarto-table-cell-role="th">Max_Antique</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>36.43413</td>
<td>34.0</td>
<td>50</td>
<td>13</td>
<td>-1</td>
<td>136</td>
</tr>
</tbody>
</table>

</div>
</div>
</div></li>
</ul>
<p><em>- La antigüedad de las viviendas en el año de venta varía desde un mínimo de -1 año (lo cual es inusual) hasta un máximo de 136 años, con un valor medio de aproximadamente 36.43 meses y una mediana de 34 meses. Estos estadísticos proporcionan información sobre la distribución de la antigüedad de las viviendas en el conjunto de datos, lo que puede ser relevante para comprender la historia y la calidad de las propiedades en venta. La presencia de un valor negativo para la antigüedad podría requerir una investigación adicional o corrección en los datos.</em></p>
<ul>
<li>Relación Baños por Habitaciones: Determinar la relación entre el número de baños y el número de habitaciones para evaluar la comodidad de la vivienda Rooms = (Full_Bath + Half_Bath) / TotRms_AbvGrd).</li>
</ul>
<div class="cell" data-execution_count="6">
<div class="cell-output cell-output-display" data-execution_count="66">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Mean_Rooms</th>
<th data-quarto-table-cell-role="th">Median_Rooms</th>
<th data-quarto-table-cell-role="th">First_Rooms</th>
<th data-quarto-table-cell-role="th">Last_Rooms</th>
<th data-quarto-table-cell-role="th">Min_Rooms</th>
<th data-quarto-table-cell-role="th">Max_Rooms</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1.62225</td>
<td>2.0</td>
<td>1.0</td>
<td>2.111111</td>
<td>0.0</td>
<td>4.25</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>-<em>La variable “Rooms” muestra una amplia variabilidad en la relación entre baños y habitaciones en las viviendas del conjunto de datos. La media de alrededor de 1.62225 sugiere que, en promedio, hay más habitaciones que baños, pero los valores mínimo y máximo indican que hay casos inusuales, incluyendo viviendas con cero baños por habitación y viviendas con una alta proporción de baños en relación con las habitaciones. Esta variable puede ser relevante para evaluar la comodidad y el diseño de las viviendas en venta.</em></p>
<ul>
<li>Tamaño del Garaje por Coche: Calcular el tamaño promedio del garaje por coche dividiendo el área del garaje por la cantidad de coches que puede albergar (Garagexcar= Garage_Area / Garage_Cars).</li>
</ul>
<div class="cell" data-execution_count="7">
<div class="cell-output cell-output-display" data-execution_count="67">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Mean_Garagexcar</th>
<th data-quarto-table-cell-role="th">Median_Garagexcar</th>
<th data-quarto-table-cell-role="th">First_Garagexcar</th>
<th data-quarto-table-cell-role="th">Last_Garagexcar</th>
<th data-quarto-table-cell-role="th">Min_Garagexcar</th>
<th data-quarto-table-cell-role="th">Max_Garagexcar</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>272.233574</td>
<td>264.0</td>
<td>264.0</td>
<td>216.666667</td>
<td>100.0</td>
<td>924.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><em>-En cuanto a la variable “Garagexcar” muestra una variabilidad en el tamaño del garaje por coche en las viviendas del conjunto de datos. La media y la mediana indican que, en promedio, hay un espacio razonablemente amplio en el garaje para cada coche, pero hay casos donde el tamaño del garaje por coche es significativamente mayor o menor.</em></p>
<p>________________________________________________________________________________________________</p>
</section>
<section id="gráficas" class="level1">
<h1>Gráficas</h1>
<div class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<p><img src="Avance%204_files/figure-html/cell-9-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code></code></pre>
</div>
</div>
<div class="cell" data-execution_count="9">
<div class="cell-output cell-output-display">
<p><img src="Avance%204_files/figure-html/cell-10-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code></code></pre>
</div>
</div>
<div class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<p><img src="Avance%204_files/figure-html/cell-11-output-1.png" width="1152" height="576"></p>
</div>
</div>
<p><em>La grafica de barras proporciona una representación visual de la distribución de viviendas en diferentes vecindarios, lo que puede ser útil para comprender mejor la distribución.</em></p>
<div class="cell" data-execution_count="11">
<div class="cell-output cell-output-display">
<p><img src="Avance%204_files/figure-html/cell-12-output-1.png" width="1152" height="576"></p>
</div>
</div>
<p><em>Este gráfico te permite explorar cómo varían los precios por metro cuadrado en diferentes vecindarios, lo que permite tomar decisiones relacionadas con el área de la vivienda.</em></p>
</section>
<section id="regresión-lineal" class="level1">
<h1>Regresión Lineal</h1>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> mean_squared_error</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>ames_housing <span class="op">=</span> pd.read_csv(<span class="st">"ames.csv"</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>features <span class="op">=</span> ames_housing[[<span class="st">'Year_Built'</span>, <span class="st">'Lot_Frontage'</span>]]</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>target <span class="op">=</span> ames_housing[<span class="st">'Sale_Price'</span>]</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(features, target, test_size<span class="op">=</span><span class="fl">0.4</span>, random_state<span class="op">=</span><span class="dv">4321</span>)</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> LinearRegression()</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>model.fit(X_train, y_train)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> model.predict(X_test)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>mse <span class="op">=</span> mean_squared_error(y_test, y_pred)</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Error cuadrático medio:"</span>, mse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Error cuadrático medio: 4281033287.061947</code></pre>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>